Bubble Sort implementation
NoTengoBattery/ruby-1 pull request #1
Opened 2021-01-04 16:19 UTC by NoTengoBattery

This pull request contains the source code of the Bubble Sort sorting algorithm, written in Ruby. The following features are included:

- Sort any array using the criteria provided by the user
- Rspec test to test and enforce the functionality
- Documentation and instructions for usage

Any comments are welcome. If you have any problem with this code, discuss it in this pull request. For code in the master/main branch, please open a GitHub Issue [here](https://github.com/NoTengoBattery/ruby-1/issues).

2021-01-05 15:47 UTC, Temmarie approved these changes
## Changes Required! :recycle:

### Hi @NoTengoBattery and @ixboy  ! :wave: :wave:

#### You have done well so far :clap: However, there are changes required for you to make in order for this project to be approved. Kindly work on them and submit them for another code review.


**Recommended**

- [ ] You've done an amazing job so far, but you skipped on the `bubble_sort` method. Please add it and request another review.

__Kindly make the necessary changes and submit another code review request.__
_Feel free to reach me on slack for any inquiries about this review._ :wink:
__Grace Tamara Ekunola __
[GitHub](https://github.com/temmarie) | [LinkedIn](https://www.linkedin.com/in/ekunola-grace/) | [Twitter](https://twitter.com/TemmarieW)

2021-01-05 16:16 UTC, Temmarie requested changes
## Changes Required! :recycle:

### Hi @NoTengoBattery and @ixboy  ! :wave: :wave:

#### You have done well so far :clap: However, there are changes required for you to make in order for this project to be approved. Kindly work on them and submit them for another code review.


**Recommended**

- [ ] You've done an amazing job so far, but you skipped on the `bubble_sort` method. Please add it and request another review.

__Kindly make the necessary changes and submit another code review request.__
_Feel free to reach me on slack for any inquiries about this review._ :wink:
__Grace Tamara Ekunola __
[GitHub](https://github.com/temmarie) | [LinkedIn](https://www.linkedin.com/in/ekunola-grace/) | [Twitter](https://twitter.com/TemmarieW)

2021-01-05 18:51 UTC, ixboy commented
Hello @Temmarie  and happy new year, first of all, thanks a lot for your review of our project and thanks for the compliments, I just wanted to clarify that we did not skip the __bubble_sort__   we actually have combined all the functionalities of the _bubble_sort_ and the _bubble_sort_by_ into one code that does everything, that's why we didn't implement both codes at the beginning and I admit that was a mistake from our side because we did not follow the requirements.
but we have completed all the requirements now and separated them into two different codes with different functions.

2021-01-08 15:12 UTC, Georjane approved these changes
## Status: PR Approved 💯 🥇 
### Hi Team @NoTengoBattery and @ixboy ✋🏽 
Congratulations on successfully completing this project. It's a thumbs up for me. 👍🏽 You can go ahead and merge this pull request.

Good luck on your next project and Happy Coding 💻

2021-01-08 20:19 UTC, merged